import {
  Asterisk,
  Blocks,
  Church,
  Compass,
  Crown,
  Dna,
  DollarSign,
  Eye,
  Factory,
  Flag,
  Flame,
  Gavel,
  Globe,
  Hammer,
  Heart,
  Landmark,
  Leaf,
  Scale,
  Sprout,
  Sunrise,
  Venus,
  Wind,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const AXIS_ICONS: Record<string, LucideIcon> = {
  communism: Hammer,
  capitalism: DollarSign,
  progressive: Sunrise,
  conservative: Landmark,
  internationalism: Globe,
  nationalism: Flag,
  ecology: Leaf,
  production: Factory,
  regulation: Scale,
  laissez_faire: Wind,
  rehabilitative_justice: Heart,
  punitive_justice: Gavel,
  revolution: Flame,
  reform: Wrench,
  constructivism: Blocks,
  essentialism: Dna,
  feminism: Venus,
  veganism: Sprout,
  anarchism: Asterisk,
  monarchism: Crown,
  religion: Church,
  complotism: Eye,
  pragmatism: Compass,
};

export function iconForAxis(axis: string): LucideIcon {
  return AXIS_ICONS[axis] ?? Asterisk;
}
